services:
  ollama-openai-proxy:
    image: ghcr.io/olegshulyakov/ollama-openai-proxy:latest
    container_name: ollama-openai-proxy
    restart: on-failure:5
    mem_limit: 64m
    security_opt:
      - no-new-privileges:true
    ports:
      - 11434:11434
    environment:
      - PROXY_PORT=11434
      - OPENAI_API_BASE_URL=https://api.openai.com
      - OPENAI_ALLOWED_MODELS=gpt-4o,gpt-3.5-turbo
